// <auto-generated />
using Catalogs.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalogs.Infra.Data.Migrations
{
    [DbContext(typeof(ProductsContext))]
    partial class ProductsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Catalogs.Domain.Entities.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1L,
                            Brand = "Apple",
                            Description = "An apple mobile which is nothing like apple",
                            Price = 549m,
                            Stock = 94,
                            Thumbnail = "https://dummyjson.com/image/i/products/1/thumbnail.jpg",
                            Title = "iPhone9"
                        },
                        new
                        {
                            ProductId = 2L,
                            Brand = "Apple",
                            Description = "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
                            Price = 899m,
                            Stock = 34,
                            Thumbnail = "https://dummyjson.com/image/i/products/2/thumbnail.jpg",
                            Title = "iPhone X"
                        },
                        new
                        {
                            ProductId = 3L,
                            Brand = "Samsung",
                            Description = "Samsung's new variant which goes beyond Galaxy to the Universe",
                            Price = 1249m,
                            Stock = 36,
                            Thumbnail = "https://dummyjson.com/image/i/products/3/thumbnail.jpg",
                            Title = "Samsung Universe 9"
                        },
                        new
                        {
                            ProductId = 4L,
                            Brand = "OPPO",
                            Description = "OPPO F19 is officially announced on April 2021.",
                            Price = 280m,
                            Stock = 123,
                            Thumbnail = "https://dummyjson.com/image/i/products/4/thumbnail.jpg",
                            Title = "OPPOF19"
                        },
                        new
                        {
                            ProductId = 5L,
                            Brand = "Huawei",
                            Description = "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
                            Price = 499m,
                            Stock = 32,
                            Thumbnail = "https://dummyjson.com/image/i/products/5/thumbnail.jpg",
                            Title = "Huawei P30"
                        },
                        new
                        {
                            ProductId = 6L,
                            Brand = "Apple",
                            Description = "MacBook Pro 2021 with mini-LED display may launch between September, November",
                            Price = 1749m,
                            Stock = 83,
                            Thumbnail = "https://dummyjson.com/image/i/products/6/thumbnail.png",
                            Title = "MacBook Pro"
                        },
                        new
                        {
                            ProductId = 7L,
                            Brand = "Samsung",
                            Description = "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
                            Price = 1499m,
                            Stock = 50,
                            Thumbnail = "https://dummyjson.com/image/i/products/7/thumbnail.jpg",
                            Title = "Samsung Galaxy Book"
                        },
                        new
                        {
                            ProductId = 8L,
                            Brand = "Microsoft Surface",
                            Description = "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
                            Price = 1499m,
                            Stock = 68,
                            Thumbnail = "https://dummyjson.com/image/i/products/8/thumbnail.jpg",
                            Title = "Microsoft Surface Laptop 4"
                        },
                        new
                        {
                            ProductId = 9L,
                            Brand = "Infinix",
                            Description = "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
                            Price = 1099m,
                            Stock = 96,
                            Thumbnail = "https://dummyjson.com/image/i/products/9/thumbnail.jpg",
                            Title = "Infinix INBOOK"
                        },
                        new
                        {
                            ProductId = 10L,
                            Brand = "HP Pavilion",
                            Description = "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
                            Price = 1099m,
                            Stock = 89,
                            Thumbnail = "https://dummyjson.com/image/i/products/10/thumbnail.jpeg",
                            Title = "HP Pavilion 15-DK1056WM"
                        },
                        new
                        {
                            ProductId = 11L,
                            Brand = "Impression of Acqua Di Gio",
                            Description = "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
                            Price = 13m,
                            Stock = 65,
                            Thumbnail = "https://dummyjson.com/image/i/products/11/thumbnail.jpg",
                            Title = "perfume Oil"
                        },
                        new
                        {
                            ProductId = 12L,
                            Brand = "Royal_Mirage",
                            Description = "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
                            Price = 40m,
                            Stock = 52,
                            Thumbnail = "https://dummyjson.com/image/i/products/12/thumbnail.jpg",
                            Title = "Brown Perfume"
                        },
                        new
                        {
                            ProductId = 13L,
                            Brand = "Fog Scent Xpressio",
                            Description = "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
                            Price = 13m,
                            Stock = 61,
                            Thumbnail = "https://dummyjson.com/image/i/products/13/thumbnail.webp",
                            Title = "Fog Scent Xpressio Perfume"
                        },
                        new
                        {
                            ProductId = 14L,
                            Brand = "Al Munakh",
                            Description = "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil",
                            Price = 120m,
                            Stock = 114,
                            Thumbnail = "https://dummyjson.com/image/i/products/14/thumbnail.jpg",
                            Title = "Non-Alcoholic Concentrated Perfume Oil"
                        },
                        new
                        {
                            ProductId = 15L,
                            Brand = "Lord - Al-Rehab",
                            Description = "Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
                            Price = 30m,
                            Stock = 105,
                            Thumbnail = "https://dummyjson.com/image/i/products/15/thumbnail.jpg",
                            Title = "Eau De Perfume Spray"
                        },
                        new
                        {
                            ProductId = 16L,
                            Brand = "L'Oreal Paris",
                            Description = "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
                            Price = 19m,
                            Stock = 110,
                            Thumbnail = "https://dummyjson.com/image/i/products/16/thumbnail.jpg",
                            Title = "Hyaluronic Acid Serum"
                        },
                        new
                        {
                            ProductId = 17L,
                            Brand = "Hemani Tea",
                            Description = "Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,",
                            Price = 12m,
                            Stock = 78,
                            Thumbnail = "https://dummyjson.com/image/i/products/17/thumbnail.jpg",
                            Title = "Tree Oil 30ml"
                        },
                        new
                        {
                            ProductId = 18L,
                            Brand = "ROREC White Rice",
                            Description = "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
                            Price = 40m,
                            Stock = 88,
                            Thumbnail = "https://dummyjson.com/image/i/products/18/thumbnail.jpg",
                            Title = "Oil Free Moisturizer 100ml"
                        },
                        new
                        {
                            ProductId = 19L,
                            Brand = "ROREC White Rice",
                            Description = "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m",
                            Price = 46m,
                            Stock = 54,
                            Thumbnail = "https://dummyjson.com/image/i/products/19/thumbnail.jpg",
                            Title = "Skin Beauty Serum"
                        },
                        new
                        {
                            ProductId = 20L,
                            Brand = "Fair & Clear",
                            Description = "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.",
                            Price = 70m,
                            Stock = 140,
                            Thumbnail = "https://dummyjson.com/image/i/products/20/thumbnail.jpg",
                            Title = "Freckle Treatment Cream- 15gm"
                        },
                        new
                        {
                            ProductId = 21L,
                            Brand = "Saaf & Khaas",
                            Description = "Fine quality Branded Product Keep in a cool and dry place",
                            Price = 20m,
                            Stock = 133,
                            Thumbnail = "https://dummyjson.com/image/i/products/21/thumbnail.png",
                            Title = "Daal Masoor 500 grams"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
